---
source-git-commit: fd3857e93dbaaf7ffce97715b77ee63e8460af16
workflow-type: tm+mt
source-wordcount: '130'
ht-degree: 0%

---
grafiek LR
subgraph CF [&quot;<b> Stichting van Commerce </b>&quot;]
richting TB
CS ([ &quot;Storefront&quot;])
CB ([ &quot;Backend&quot;])
end

     SC ([&quot;de Schakelaar van de Diensten&quot;]) 
    
     subgraph SaaS [&quot;&lt;b>SaaS&lt;/b>&quot;] 
     richting TB 
     Diensten ([&quot;&lt;b>Services&lt;/b>&lt;br/>Live Onderzoek&lt;br/>Product Recommendations&lt;br/>Catalog Service&lt;br/>Payment Services&quot;) 
     Integraties (&quot; Integraties&lt;/b>&lt;br/>Data Connection&lt;br/>AEM Assets&quot;) 
     eind 
    
     CF &lt;—> SC &lt;—> SaaS
    
    classDef foundationStyle vullen:#FFF9E6,slag:#C7B88A,slag-breedte:3px,color:#000 00,rx:15,ry:15,font-family:Adobe Clean
    classDef sasStyle fill:#FFE6F0,stroke:#D4A6B8,stroke-width:3px,color:#00000,rx:15,ry:15,color font-family:Adobe Clean
    classDef boxStyle fill:#FFFFFF,stroke:#00000,stroke-width:2px,color:#00000,rx:15,ry:15,font-family:Adobe Clean&lt;ph id=&#39;639 &quot;/>classDef connectorStyle fill:#4A4A4A,stroke:#4A4A4A,stroke-width:2px,color:#FFFFFF,rx:15,ry:15,font-family:Adobe Clean
    
    class CF foundationStyle
    class SaaS sasStyle
    klasse CS,CB,Services,Integrations boxStyle
    klasse SC-connectorStyle
    